#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'running pre-commiting checks...'

npx lint-staged

# Skip Husky checks in production and CI
if [ "$NODE_ENV" = "production" ] || [ "$CI" = "true" ]; then
  exit 0;
fi